language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: jy0FCaf+2mVkZmHVKSoSR8sKD+U9zEnzWiO5fm/B2VNvgsNnGYSc25d0ST5ENIEIX+YS0QReq8SdkKsoSwKYgq+Asg5i776kOYikxWQOoy1DrdXaVYpQUfFG1nlEm7mdEIAAEvyahiEArFLRoVRSyAU3TSz7Jj22BbsTf4kNUn2tqFbFUruFJ/+OxTE8i9bMEcddp63Nb2ZarVvll1oW3QQHiREniRfGD5pkLgJUtN+mvFKBeAtedxZpEqd8RaGp8FygyyC5zDxhXPhlpbsmPFr225n9dvyWvwDp+6FSaLjOoAgCU7sDMnik0nSas7I3XOIQZXZYwCJYUDsSepoIZJjk5b6WLo0wOuZBXqvGdD4E4Rhkk0/BoJdth0xbMPMZAr1gdMJNK9jlB5lx6M8vIcXHXcKMWN7i0AQkAqQZjvUgGSFbKeymeyczbFm6xcR57GplzgTBNE7QI7hFa+Tq90MUUQ0S9GdTpO73BywGmsp+NEBYwOmBm7XI0OcUFOp21KoyaJ3nhamqXb+KvFWLa+tH61VVq7RDxg5MfYG1yKisUZh4+j2Q3C8gPo6ORJSXM9l6nc2ipEeQwQG3Qk3XuVfxAUj0sEG0/kAJbfcXXXtHnbsom8mscvSvRpVJIq7wnXO6GHPRvZgNMLj2Gwa30pc5Km4ZslIMBflo2ROSR10=
  app: stepney-volunteers-staging
  on:
    repo: stepneybankstables/StepneyVolunteers
    
