language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Yvg3VkcqnYpZWnIUQPhHK4Zh8fUt2kJVpv0ofVePy32s8MEY9GmpHm50HVNCAgIEDE5fU/rthWoY8bKnmqfotGUIcdMGDvNv+SpN6uBh06LmyZeOtvkaIB4ntxZcuf18DXcG7j7gDeRAZZo3kwADK7zAJQyrSNmogcJVUbV1uPyIAxqQWTDvfg54WstmCaWhM3QqQWZGRUXNwEea8KgEHtmzy5zZLt++beLDy0HG2dwMtvAg0BRxzUoNdr5E5Lps2DC+P309aTQtKCTaqtMADQ079C2ZffOyt412AlOadSsG0v0thHBtdQaqmp2qCAxpXp7hlJssYcgJWTWr48uQMHIZxtB6EwSVRjbkQDOiLqFlxAMKo+y+nBaVBJ75986JMMzVj6kLhsMBEVDysBp5MhhS5xTqEJBaAeoXAxlJzD00SfCHBMdCTgDwD+bBf5Cj5A1YlFawI6fKZr7qh0ET2j7FFqJGPZJjjxBDtBCzC7dkViOH9Q7CFYDbbg7w7LgLnO+lTnPCc8EgB6BNWtO8PVJOuiLWRqizKtWCDNXtGR23CTAEVqh1sDFpCHxRL1geeLmvlvW7tZH0YtedEz3zonMqXvw3BHFg7rivLqTGCfOFTdW/0u72348hyDDie1LIvcnuQ2mUdziQVCrQ+1NDLQvSOchoq8ZQp2lJJAJNUS4=
  app: stepney-volunteers-staging
  on:
    repo: stepneybankstables/StepneyVolunteers
    
